"""A source that invents deterministic items — the end-to-end test of the platform.

This exists so the whole pipeline (collect → hash → upsert → enqueue → deliver →
ledger → GlitchTip → Healthchecks) can be proven correct *before* any real site's
authentication, pagination or markup is in the picture. When Studeo breaks later,
running ``pap run fake`` immediately answers "is it the platform or the site?"

The items are deterministic, so a second run finds exactly the same ones and must
enqueue nothing. That is the idempotency guarantee, demonstrated rather than
asserted.

``--boom`` makes it raise on purpose: the only way to confirm that a failure
really reaches GlitchTip with the right tags and lands its event id on the run
row is to cause one.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Iterable

from ..core.models import Item
from ..core.registry import register
from .base import BaseSource


class FakeSourceError(RuntimeError):
    """Raised by ``--boom`` to exercise the error-reporting path."""


@register
class FakeSource(BaseSource):
    name = "fake"

    def __init__(self, settings, *, count: int = 3, boom: bool = False) -> None:
        super().__init__(settings)
        self.count = count
        self.boom = boom

    def collect(self) -> Iterable[Item]:
        if self.boom:
            raise FakeSourceError(
                "deliberate failure from `pap run fake --boom` — if you are reading this "
                "in GlitchTip, error reporting works"
            )

        # Fixed origin, so external_id and content_hash are stable across runs.
        origin = datetime(2026, 1, 1, tzinfo=timezone.utc)
        for index in range(1, self.count + 1):
            due = origin + timedelta(days=7 * index)
            yield Item(
                source=self.name,
                external_id=f"fake-{index:03d}",
                title=f"Atividade de teste {index}",
                kind="activity",
                url=f"https://example.invalid/atividade/{index}",
                due_at=due,
                module_code="54/2025",
                discipline_external_id="disc-001",
                discipline_name="Disciplina de Teste",
                payload={
                    "summary": (
                        f"Item {index} generated by the fake source to verify the pipeline "
                        f"end to end. It carries no real data."
                    ),
                    "due_at": due.isoformat(),
                },
            )
